---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jraynor.
--- DateTime: 8/15/2023 10:24 PM
---

print("hello world")

local a = 1
local b = 2

local c = a + b

print(c)

function fib(n)
    if n < 2 then
        return n
    end
    return fib(n - 2) + fib(n - 1)
end

print(fib(69))

local function test()
    print("test")
end

test()